### ISSUE TITLE
Серый экран на вкалдке "Мои счета"

### ISSUE THREAD

**Issue by vaimon** [Den0110/fin-clever#7]
<img width="203" alt="image" src="https://user-images.githubusercontent.com/28728097/161817084-ba23970a-b0a7-4e48-a60f-c7d735dbc9aa.png">

В логи при этом выпадает вот такое:
```
04-05 17:34:06.007  6181  6217 I flutter : type 'StackParentData' is not a subtype of type 'FlexParentData' in type cast
04-05 17:34:06.011  6181  6217 I flutter : #0      Flexible.applyParentData (package:flutter/src/widgets/basic.dart:4973)
04-05 17:34:06.011  6181  6217 I flutter : #1      RenderObjectElement._updateParentData (package:flutter/src/widgets/framework.dart:5941)
04-05 17:34:06.011  6181  6217 I flutter : #2      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:5961)
04-05 17:34:06.011  6181  6217 I flutter : #3      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5635)
04-05 17:34:06.011  6181  6217 I flutter : #4      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6283)
04-05 17:34:06.011  6181  6217 I flutter : #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
04-05 17:34:06.011  6181  6217 I flutter : #6      Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
04-05 17:34:06.011  6181  6217 I flutter : #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
04-05 17:34:06.011  6181  6217 I flutter : #8      Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
04-05 17:34:06.011  6181  6217 I flutter : #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
04-05 17:34:06.011  6181  6217 I flutter : #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
04-05 17:34:06.011  6181  6217 I flutter : #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
04-05 17:34:06.012  6181  6217 I flutter : #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
04-05 17:34:06.012  6181  6217 I flutter : #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
04-05 17:34:06.012  6181  6217 I flutter : #14     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928)
04-05 17:34:06.012  6181  6217 I flutter : #15     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
04-05 17:34:06.012  6181  6217 I flutter : #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
04-05 17:34:06.012  6181  6217 I flutter : #17     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4919)
04-05 17:34:06.012  6181  6217 I flutter : #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
04-05 17:34:06.012  6181  6217 I flutter : #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
04-05 17:34:06.012  6181  6217 I flutter : #20     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
04-05 17:34:06.012  6181  6217 I flutter : #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
04-05 17:34:06.012  6181  6217 I flutter : #22     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928)
04-05 17:34:06.012  6181  6217 I flutter : #23     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
04-05 17:34:06.012  6181  6217 I flutter : #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
04-05 17:34:06.012  6181  6217 I flutter : #25     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4919)
04-05 17:34:06.012  6181  6217 I flutter : #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
04-05 17:34:06.012  6181  6217 I flutter : #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
04-05 17:34:06.012  6181  6217 I flutter : #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
04-05 17:34:06.012  6181  6217 I flutter : #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
04-05 17:34:06.012  6181  6217 I flutter : #30     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
04-05 17:34:06.012  6181  6217 I flutter : #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
04-05 17:34:06.012  6181  6217 I flutter : #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
04-05 17:34:06.012  6181  6217 I flutter : #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
04-05 17:34:06.012  6181  6217 I flutter : #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
04-05 17:34:06.012  6181  6217 I flutter : #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
04-05 17:34:06.012  6181  6217 I flutter : #36     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
04-05 17:34:06.012  6181  6217 I flutter : #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
04-05 17:34:06.012  6181  6217 I flutter : #38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
04-05 17:34:06.012  6181  6217 I flutter : #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
04-05 17:34:06.012  6181  6217 I flutter : #40     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
04-05 17:34:06.012  6181  6217 I flutter : #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
04-05 17:34:06.012  6181  6217 I flutter : #42     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
04-05 17:34:06.012  6181  6217 I flutter : #43     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
04-05 17:34:06.012  6181  6217 I flutter : #44     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
04-05 17:34:06.012  6181  6217 I flutter : #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
04-05 17:34:06.013  6181  6217 I flutter : #46     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
04-05 17:34:06.013  6181  6217 I flutter : #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
04-05 17:34:06.013  6181  6217 I flutter : #48     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
04-05 17:34:06.013  6181  6217 I flutter : #49     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
04-05 17:34:06.013  6181  6217 I flutter : #50     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
04-05 17:34:06.013  6181  6217 I flutter : #51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
04-05 17:34:06.013  6181  6217 I flutter : #52     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
04-05 17:34:06.013  6181  6217 I flutter : #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
04-05 17:34:06.013  6181  6217 I flutter : #54     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
04-05 17:34:06.013  6181  6217 I flutter : #55     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
04-05 17:34:06.013  6181  6217 I flutter : #56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
04-05 17:34:06.013  6181  6217 I flutter : #57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
04-05 17:34:06.013  6181  6217 I flutter : #58     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422)
04-05 17:34:06.013  6181  6217 I flutter : #59     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433)
04-05 17:34:06.013  6181  6217 I flutter : #60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
04-05 17:34:06.013  6181  6217 I flutter : #61     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
04-05 17:34:06.013  6181  6217 I flutter : #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
04-05 17:34:06.013  6181  6217 I flutter : #63     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928)
04-05 17:34:06.013  6181  6217 I flutter : #64     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
04-05 17:34:06.013  6181  6217 I flutter : #65     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
04-05 17:34:06.013  6181  6217 I flutter : #66     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4919)
04-05 17:34:06.013  6181  6217 I flutter : #67     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
04-05 17:34:06.013  6181  6217 I flutter : #68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
04-05 17:34:06.013  6181  6217 I flutter : #69     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
04-05 17:34:06.013  6181  6217 I flutter : #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
04-05 17:34:06.013  6181  6217 I flutter : #71     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
04-05 17:34:06.013  6181  6217 I flutter : #72     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
04-05 17:34:06.013  6181  6217 I flutter : #73     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
04-05 17:34:06.013  6181  6217 I flutter : #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
04-05 17:34:06.014  6181  6217 I flutter : #75     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422)
04-05 17:34:06.014  6181  6217 I flutter : #76     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433)
04-05 17:34:06.014  6181  6217 I flutter : #77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
04-05 17:34:06.014  6181  6217 I flutter : #78     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422)
04-05 17:34:06.014  6181  6217 I flutter : #79     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433)
04-05 17:34:06.014  6181  6217 I flutter : #80     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
04-05 17:34:06.014  6181  6217 I flutter : #81     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
04-05 17:34:06.014  6181  6217 I flutter : #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
04-05 17:34:06.014  6181  6217 I flutter : #83     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
04-05 17:34:06.014  6181  6217 I flutter : #84     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
04-05 17:34:06.014  6181  6217 I flutter : #85     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
04-05 17:34:06.014  6181  6217 I flutter : #86     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
04-05 17:34:06.014  6181  6217 I flutter : #87     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
04-05 17:34:06.014  6181  6217 I flutter : #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
04-05 17:34:06.014  6181  6217 I flutter : #89     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
04-05 17:34:06.014  6181  6217 I flutter : #90     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
04-05 17:34:06.014  6181  6217 I flutter : #91     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
04-05 17:34:06.014  6181  6217 I flutter : #92     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
04-05 17:34:06.014  6181  6217 I flutter : #93     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
04-05 17:34:06.014  6181  6217 I flutter : #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
04-05 17:34:06.014  6181  6217 I flutter : #95     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
04-05 17:34:06.014  6181  6217 I flutter : #96     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
04-05 17:34:06.014  6181  6217 I flutter : #97     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
04-05 17:34:06.014  6181  6217 I flutter : #98     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
04-05 17:34:06.015  6181  6217 I flutter : #99     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422)
04-05 17:34:06.015  6181  6217 I flutter : Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
```

**Comment by Den0110** [comment]
Баг исправлен. Сборку на гугл-диске обновил.

**Comment by vaimon** [comment]
> Баг исправлен. Сборку на гугл-диске обновил.

@Den0110 В любом случае проверяться будет сборка, предоставленная изначально. На будущее, менять что-то на диске  после сдачи (и до окончания проверки) - не очень хорошая идея, которая может повлечь определённые последствия. В данном случае в issue я кинул развёрнутые логи, чтобы вы просто знали, что такая проблема существует)

**Comment by Den0110** [comment]
Хорошо, учту
